/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MunicipioIbgeIdRouteImport } from './routes/municipio.$ibgeId'
import { Route as DebugOpenaiRouteImport } from './routes/debug.openai'
import { Route as DebugApifyRouteImport } from './routes/debug.apify'
import { Route as ApiProspectRouteImport } from './routes/api/prospect'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicProspectRouteImport } from './routes/api/public/prospect'
import { Route as ApiDebugOpenaiRouteImport } from './routes/api/debug.openai'
import { Route as ApiDebugApifyRouteImport } from './routes/api/debug.apify'
import { Route as ApiAdminQueryTestRouteImport } from './routes/api/admin/query-test'
import { Route as ApiAdminImportRouteImport } from './routes/api/admin/import'
import { Route as AuthenticatedAdminScoreRouteImport } from './routes/_authenticated/admin.score'
import { Route as AuthenticatedAdminQueriesRouteImport } from './routes/_authenticated/admin.queries'
import { Route as AuthenticatedAdminProspeccaoRouteImport } from './routes/_authenticated/admin.prospeccao'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminMunicipiosIndexRouteImport } from './routes/_authenticated/admin.municipios.index'
import { Route as AuthenticatedAdminMunicipiosIbgeIdRouteImport } from './routes/_authenticated/admin.municipios.$ibgeId'

const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipioIbgeIdRoute = MunicipioIbgeIdRouteImport.update({
  id: '/municipio/$ibgeId',
  path: '/municipio/$ibgeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugOpenaiRoute = DebugOpenaiRouteImport.update({
  id: '/openai',
  path: '/openai',
  getParentRoute: () => DebugRoute,
} as any)
const DebugApifyRoute = DebugApifyRouteImport.update({
  id: '/apify',
  path: '/apify',
  getParentRoute: () => DebugRoute,
} as any)
const ApiProspectRoute = ApiProspectRouteImport.update({
  id: '/api/prospect',
  path: '/api/prospect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicProspectRoute = ApiPublicProspectRouteImport.update({
  id: '/api/public/prospect',
  path: '/api/public/prospect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugOpenaiRoute = ApiDebugOpenaiRouteImport.update({
  id: '/api/debug/openai',
  path: '/api/debug/openai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugApifyRoute = ApiDebugApifyRouteImport.update({
  id: '/api/debug/apify',
  path: '/api/debug/apify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQueryTestRoute = ApiAdminQueryTestRouteImport.update({
  id: '/api/admin/query-test',
  path: '/api/admin/query-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImportRoute = ApiAdminImportRouteImport.update({
  id: '/api/admin/import',
  path: '/api/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminScoreRoute = AuthenticatedAdminScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQueriesRoute =
  AuthenticatedAdminQueriesRouteImport.update({
    id: '/queries',
    path: '/queries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProspeccaoRoute =
  AuthenticatedAdminProspeccaoRouteImport.update({
    id: '/prospeccao',
    path: '/prospeccao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMunicipiosIndexRoute =
  AuthenticatedAdminMunicipiosIndexRouteImport.update({
    id: '/municipios/',
    path: '/municipios/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMunicipiosIbgeIdRoute =
  AuthenticatedAdminMunicipiosIbgeIdRouteImport.update({
    id: '/municipios/$ibgeId',
    path: '/municipios/$ibgeId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/debug': typeof DebugRouteWithChildren
  '/manual': typeof ManualRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/prospect': typeof ApiProspectRoute
  '/debug/apify': typeof DebugApifyRoute
  '/debug/openai': typeof DebugOpenaiRoute
  '/municipio/$ibgeId': typeof MunicipioIbgeIdRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/prospeccao': typeof AuthenticatedAdminProspeccaoRoute
  '/admin/queries': typeof AuthenticatedAdminQueriesRoute
  '/admin/score': typeof AuthenticatedAdminScoreRoute
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/query-test': typeof ApiAdminQueryTestRoute
  '/api/debug/apify': typeof ApiDebugApifyRoute
  '/api/debug/openai': typeof ApiDebugOpenaiRoute
  '/api/public/prospect': typeof ApiPublicProspectRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/municipios/$ibgeId': typeof AuthenticatedAdminMunicipiosIbgeIdRoute
  '/admin/municipios/': typeof AuthenticatedAdminMunicipiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/debug': typeof DebugRouteWithChildren
  '/manual': typeof ManualRoute
  '/api/prospect': typeof ApiProspectRoute
  '/debug/apify': typeof DebugApifyRoute
  '/debug/openai': typeof DebugOpenaiRoute
  '/municipio/$ibgeId': typeof MunicipioIbgeIdRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/prospeccao': typeof AuthenticatedAdminProspeccaoRoute
  '/admin/queries': typeof AuthenticatedAdminQueriesRoute
  '/admin/score': typeof AuthenticatedAdminScoreRoute
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/query-test': typeof ApiAdminQueryTestRoute
  '/api/debug/apify': typeof ApiDebugApifyRoute
  '/api/debug/openai': typeof ApiDebugOpenaiRoute
  '/api/public/prospect': typeof ApiPublicProspectRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/municipios/$ibgeId': typeof AuthenticatedAdminMunicipiosIbgeIdRoute
  '/admin/municipios': typeof AuthenticatedAdminMunicipiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/debug': typeof DebugRouteWithChildren
  '/manual': typeof ManualRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/prospect': typeof ApiProspectRoute
  '/debug/apify': typeof DebugApifyRoute
  '/debug/openai': typeof DebugOpenaiRoute
  '/municipio/$ibgeId': typeof MunicipioIbgeIdRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/prospeccao': typeof AuthenticatedAdminProspeccaoRoute
  '/_authenticated/admin/queries': typeof AuthenticatedAdminQueriesRoute
  '/_authenticated/admin/score': typeof AuthenticatedAdminScoreRoute
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/query-test': typeof ApiAdminQueryTestRoute
  '/api/debug/apify': typeof ApiDebugApifyRoute
  '/api/debug/openai': typeof ApiDebugOpenaiRoute
  '/api/public/prospect': typeof ApiPublicProspectRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/municipios/$ibgeId': typeof AuthenticatedAdminMunicipiosIbgeIdRoute
  '/_authenticated/admin/municipios/': typeof AuthenticatedAdminMunicipiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/debug'
    | '/manual'
    | '/admin'
    | '/api/prospect'
    | '/debug/apify'
    | '/debug/openai'
    | '/municipio/$ibgeId'
    | '/admin/import'
    | '/admin/prospeccao'
    | '/admin/queries'
    | '/admin/score'
    | '/api/admin/import'
    | '/api/admin/query-test'
    | '/api/debug/apify'
    | '/api/debug/openai'
    | '/api/public/prospect'
    | '/admin/'
    | '/admin/municipios/$ibgeId'
    | '/admin/municipios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/debug'
    | '/manual'
    | '/api/prospect'
    | '/debug/apify'
    | '/debug/openai'
    | '/municipio/$ibgeId'
    | '/admin/import'
    | '/admin/prospeccao'
    | '/admin/queries'
    | '/admin/score'
    | '/api/admin/import'
    | '/api/admin/query-test'
    | '/api/debug/apify'
    | '/api/debug/openai'
    | '/api/public/prospect'
    | '/admin'
    | '/admin/municipios/$ibgeId'
    | '/admin/municipios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/debug'
    | '/manual'
    | '/_authenticated/admin'
    | '/api/prospect'
    | '/debug/apify'
    | '/debug/openai'
    | '/municipio/$ibgeId'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/prospeccao'
    | '/_authenticated/admin/queries'
    | '/_authenticated/admin/score'
    | '/api/admin/import'
    | '/api/admin/query-test'
    | '/api/debug/apify'
    | '/api/debug/openai'
    | '/api/public/prospect'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/municipios/$ibgeId'
    | '/_authenticated/admin/municipios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DebugRoute: typeof DebugRouteWithChildren
  ManualRoute: typeof ManualRoute
  ApiProspectRoute: typeof ApiProspectRoute
  MunicipioIbgeIdRoute: typeof MunicipioIbgeIdRoute
  ApiAdminImportRoute: typeof ApiAdminImportRoute
  ApiAdminQueryTestRoute: typeof ApiAdminQueryTestRoute
  ApiDebugApifyRoute: typeof ApiDebugApifyRoute
  ApiDebugOpenaiRoute: typeof ApiDebugOpenaiRoute
  ApiPublicProspectRoute: typeof ApiPublicProspectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipio/$ibgeId': {
      id: '/municipio/$ibgeId'
      path: '/municipio/$ibgeId'
      fullPath: '/municipio/$ibgeId'
      preLoaderRoute: typeof MunicipioIbgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/openai': {
      id: '/debug/openai'
      path: '/openai'
      fullPath: '/debug/openai'
      preLoaderRoute: typeof DebugOpenaiRouteImport
      parentRoute: typeof DebugRoute
    }
    '/debug/apify': {
      id: '/debug/apify'
      path: '/apify'
      fullPath: '/debug/apify'
      preLoaderRoute: typeof DebugApifyRouteImport
      parentRoute: typeof DebugRoute
    }
    '/api/prospect': {
      id: '/api/prospect'
      path: '/api/prospect'
      fullPath: '/api/prospect'
      preLoaderRoute: typeof ApiProspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/prospect': {
      id: '/api/public/prospect'
      path: '/api/public/prospect'
      fullPath: '/api/public/prospect'
      preLoaderRoute: typeof ApiPublicProspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/openai': {
      id: '/api/debug/openai'
      path: '/api/debug/openai'
      fullPath: '/api/debug/openai'
      preLoaderRoute: typeof ApiDebugOpenaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/apify': {
      id: '/api/debug/apify'
      path: '/api/debug/apify'
      fullPath: '/api/debug/apify'
      preLoaderRoute: typeof ApiDebugApifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/query-test': {
      id: '/api/admin/query-test'
      path: '/api/admin/query-test'
      fullPath: '/api/admin/query-test'
      preLoaderRoute: typeof ApiAdminQueryTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/import': {
      id: '/api/admin/import'
      path: '/api/admin/import'
      fullPath: '/api/admin/import'
      preLoaderRoute: typeof ApiAdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/score': {
      id: '/_authenticated/admin/score'
      path: '/score'
      fullPath: '/admin/score'
      preLoaderRoute: typeof AuthenticatedAdminScoreRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/queries': {
      id: '/_authenticated/admin/queries'
      path: '/queries'
      fullPath: '/admin/queries'
      preLoaderRoute: typeof AuthenticatedAdminQueriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/prospeccao': {
      id: '/_authenticated/admin/prospeccao'
      path: '/prospeccao'
      fullPath: '/admin/prospeccao'
      preLoaderRoute: typeof AuthenticatedAdminProspeccaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/municipios/': {
      id: '/_authenticated/admin/municipios/'
      path: '/municipios'
      fullPath: '/admin/municipios/'
      preLoaderRoute: typeof AuthenticatedAdminMunicipiosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/municipios/$ibgeId': {
      id: '/_authenticated/admin/municipios/$ibgeId'
      path: '/municipios/$ibgeId'
      fullPath: '/admin/municipios/$ibgeId'
      preLoaderRoute: typeof AuthenticatedAdminMunicipiosIbgeIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminProspeccaoRoute: typeof AuthenticatedAdminProspeccaoRoute
  AuthenticatedAdminQueriesRoute: typeof AuthenticatedAdminQueriesRoute
  AuthenticatedAdminScoreRoute: typeof AuthenticatedAdminScoreRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminMunicipiosIbgeIdRoute: typeof AuthenticatedAdminMunicipiosIbgeIdRoute
  AuthenticatedAdminMunicipiosIndexRoute: typeof AuthenticatedAdminMunicipiosIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminProspeccaoRoute: AuthenticatedAdminProspeccaoRoute,
  AuthenticatedAdminQueriesRoute: AuthenticatedAdminQueriesRoute,
  AuthenticatedAdminScoreRoute: AuthenticatedAdminScoreRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminMunicipiosIbgeIdRoute:
    AuthenticatedAdminMunicipiosIbgeIdRoute,
  AuthenticatedAdminMunicipiosIndexRoute:
    AuthenticatedAdminMunicipiosIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DebugRouteChildren {
  DebugApifyRoute: typeof DebugApifyRoute
  DebugOpenaiRoute: typeof DebugOpenaiRoute
}

const DebugRouteChildren: DebugRouteChildren = {
  DebugApifyRoute: DebugApifyRoute,
  DebugOpenaiRoute: DebugOpenaiRoute,
}

const DebugRouteWithChildren = DebugRoute._addFileChildren(DebugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DebugRoute: DebugRouteWithChildren,
  ManualRoute: ManualRoute,
  ApiProspectRoute: ApiProspectRoute,
  MunicipioIbgeIdRoute: MunicipioIbgeIdRoute,
  ApiAdminImportRoute: ApiAdminImportRoute,
  ApiAdminQueryTestRoute: ApiAdminQueryTestRoute,
  ApiDebugApifyRoute: ApiDebugApifyRoute,
  ApiDebugOpenaiRoute: ApiDebugOpenaiRoute,
  ApiPublicProspectRoute: ApiPublicProspectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
