/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MunicipioIbgeIdRouteImport } from './routes/municipio.$ibgeId'
import { Route as DebugApifyRouteImport } from './routes/debug.apify'
import { Route as ApiProspectRouteImport } from './routes/api/prospect'
import { Route as ApiDebugApifyRouteImport } from './routes/api/debug.apify'

const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipioIbgeIdRoute = MunicipioIbgeIdRouteImport.update({
  id: '/municipio/$ibgeId',
  path: '/municipio/$ibgeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugApifyRoute = DebugApifyRouteImport.update({
  id: '/apify',
  path: '/apify',
  getParentRoute: () => DebugRoute,
} as any)
const ApiProspectRoute = ApiProspectRouteImport.update({
  id: '/api/prospect',
  path: '/api/prospect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugApifyRoute = ApiDebugApifyRouteImport.update({
  id: '/api/debug/apify',
  path: '/api/debug/apify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRouteWithChildren
  '/api/prospect': typeof ApiProspectRoute
  '/debug/apify': typeof DebugApifyRoute
  '/municipio/$ibgeId': typeof MunicipioIbgeIdRoute
  '/api/debug/apify': typeof ApiDebugApifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRouteWithChildren
  '/api/prospect': typeof ApiProspectRoute
  '/debug/apify': typeof DebugApifyRoute
  '/municipio/$ibgeId': typeof MunicipioIbgeIdRoute
  '/api/debug/apify': typeof ApiDebugApifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRouteWithChildren
  '/api/prospect': typeof ApiProspectRoute
  '/debug/apify': typeof DebugApifyRoute
  '/municipio/$ibgeId': typeof MunicipioIbgeIdRoute
  '/api/debug/apify': typeof ApiDebugApifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/api/prospect'
    | '/debug/apify'
    | '/municipio/$ibgeId'
    | '/api/debug/apify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/api/prospect'
    | '/debug/apify'
    | '/municipio/$ibgeId'
    | '/api/debug/apify'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/api/prospect'
    | '/debug/apify'
    | '/municipio/$ibgeId'
    | '/api/debug/apify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRouteWithChildren
  ApiProspectRoute: typeof ApiProspectRoute
  MunicipioIbgeIdRoute: typeof MunicipioIbgeIdRoute
  ApiDebugApifyRoute: typeof ApiDebugApifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipio/$ibgeId': {
      id: '/municipio/$ibgeId'
      path: '/municipio/$ibgeId'
      fullPath: '/municipio/$ibgeId'
      preLoaderRoute: typeof MunicipioIbgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/apify': {
      id: '/debug/apify'
      path: '/apify'
      fullPath: '/debug/apify'
      preLoaderRoute: typeof DebugApifyRouteImport
      parentRoute: typeof DebugRoute
    }
    '/api/prospect': {
      id: '/api/prospect'
      path: '/api/prospect'
      fullPath: '/api/prospect'
      preLoaderRoute: typeof ApiProspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/apify': {
      id: '/api/debug/apify'
      path: '/api/debug/apify'
      fullPath: '/api/debug/apify'
      preLoaderRoute: typeof ApiDebugApifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DebugRouteChildren {
  DebugApifyRoute: typeof DebugApifyRoute
}

const DebugRouteChildren: DebugRouteChildren = {
  DebugApifyRoute: DebugApifyRoute,
}

const DebugRouteWithChildren = DebugRoute._addFileChildren(DebugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRouteWithChildren,
  ApiProspectRoute: ApiProspectRoute,
  MunicipioIbgeIdRoute: MunicipioIbgeIdRoute,
  ApiDebugApifyRoute: ApiDebugApifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
